:PROPERTIES:
:ID:       1f902d22-85bd-41e5-b286-0244856e245a
:END:
#+title: memory
#+filetags: computer-science

* types
:PROPERTIES:
:ANKI_NOTE_ID: 1644613749319
:END:
- stack
- heap
- registers
- text segments
- memory-mapped registers
- memory-mapped files
- nonvolatile RAM

** registers
:PROPERTIES:
:ANKI_NOTE_ID: 1644613749310
:END:
the compiler may use a {{register}} to back a variable instead of a {{region of memory}} if no memory {{address}} is needed for that variable

* page
:PROPERTIES:
:ANKI_NOTE_ID: 1644613749306
:END:
also:memory page,virtual page
a fixed-length contiguous block of virtual memory, described by a single entry in the page table. It is the smallest unit of data for memory management in a virtual memory operating system.
* page frame
:PROPERTIES:
:ID:       b1026cb9-a5e5-41c7-ba7b-b36084a864ad
:ANKI_NOTE_ID: 1644613749302
:END:
the smallest fixed-length contiguous block of physical memory into which memory pages are mapped by the operating system.
* errors
:PROPERTIES:
:ANKI_NOTE_ID: 1644613749298
:END:
- use-after-free
- buffer overflows
- and memory leaks

* alignment
:PROPERTIES:
:ANKI_NOTE_ID: 1644613749276
:END:
- byte-aligned: to be placed at an address that is a multiple of 8 bits
- describes where the bytes for a type can be stored
- the hardware constrains where a given type can be placed
  - for example: pointers point to bytes, not bits
  - if you placed a value of type T starting at bit 4 of your computer’s memory, you would have no way to refer to its location; you can create a pointer pointing only to byte 0 or byte 1 (bit 8). For this reason, all values, no matter their type, must start at a byte boundary.
  - Some values have more stringent alignment rules than just being byte-aligned. In the CPU and the memory system, memory is often accessed in blocks larger than a single byte. For example, on a 64-bit CPU, most values are accessed in chunks of 8 bytes (64 bits), with each operation starting at an 8-byte-aligned address. This is referred to as the CPU’s word size.
