:PROPERTIES:
:ID:       f608b65b-0ab7-4978-9385-0da0c8fa2d19
:END:
#+STARTUP: overview
#+VISIBILITY: folded
#+TITLE: Rust
#+filetags: :rust:

- matches macro =filter(|&c| matches!(c, 'a'|'i'|'o'|'u'|'e'|'y'))=
- [[https://docs.rs/parking_lot/0.11.1/parking_lot/index.html]]
- https://doc.rust-lang.org/stable/std/io/struct.Cursor.html
- https://docs.rs/bytes/1.0.1/bytes/buf/trait.Buf.html
- [[https://stackoverflow.com/questions/46557608/what-is-the-null-pointer-optimization-in-rust][null pointer optimization]]
- https://awesome-rust.com/#resources
- https://github.com/brson/stdx
- https://doc.rust-lang.org/std/keyword.ref.html
- https://willcrichton.net/notes/rust-memory-safety/
- https://rustype.github.io/typestate-rs/chapter_1.html
- https://github.com/DanielKeep/cargo-script
* continous integration
:PROPERTIES:
:ID:       32639ce4-25ea-41ef-9018-caa0bd47623e
:END:
- https://github.com/taiki-e/cargo-hack/
- configure your continuous integration infrastructure to test each subcrate both with the latest released versions of the other subcrates and with all of them configured to use path dependencies
- cargo-deny and cargo-audit
- If you are not running clippy as part of your CI pipeline already, you probably should be.
* COMMENT =From= and =Into=
The standard library has many conversion traits, but two of the core ones are From and Into. It might strike you as odd to have two: if we have From, why do we need Into, and vice versa? There are a couple of reasons, but let’s start with the historical one: it wouldn’t have been possible to have just one in the early days of Rust due to the coherence rules discussed in Chapter 2. Or, more specifically, what the coherence rules used to be.  Suppose you want to implement two-way conversion between some local type you have defined in your crate and some type in the standard library. You can write impl<T> From<Vec<T>> for MyType<T> and impl<T> Into<Vec<T>> for MyType<T> easily enough, but if you only had From or Into, you would have to write impl<T> From<MyType<T>> for Vec<T> or impl<T> Into<MyType<T>> for Vec<T>. However, the compiler used to reject those implementations! Only since Rust 1.41.0, when the exception for covered types was added to the coherence rules, are they legal. Before that change, it was necessary to have both traits. And since much Rust code was written before Rust 1.41.0, neither trait can be removed now.  Beyond that historical fact, however, there are also good ergonomic reasons to have both of these traits, even if we could start from scratch today. It is often significantly easier to use one or the other in different situations. For example, if you’re writing a method that takes a type that can be turned into a Foo, would you rather write fn (impl Into<Foo>) or fn<T>(T) where Foo: From<T>? And conversely, to turn a string into a syntax identifier, would you rather write Ident::from("foo") or <_ as Into<Ident>>::into("foo")? Both of these traits have their uses, and we’re better off having them both.  Given that we do have both, you may wonder which you should use in your code today. The answer, it turns out, is pretty simple: implement From, and use Into in bounds. The reason is that Into has a blanket implementation for any T that implements From, so regardless of whether a type explicitly implements From or Into, it implements Into!  Of course, as simple things frequently go, the story doesn’t quite end there. Since the compiler often has to “go through” the blanket implementation when Into is used as a bound, the reasoning for whether a type implements Into is more complicated than whether it implements From. And in some cases, the compiler is not quite smart enough to figure that puzzle out. For this reason, the ? operator at the time of writing uses From, not Into. Most of the time that doesn’t make a difference, because most types implement From, but it does mean that error types from old libraries that implement Into instead may not work with ?. As the compiler gets smarter, ? will likely be “upgraded” to use Into, at which point that problem will go away, but it's what we have for now.
* godbolt.org / cargo-asm
* destructuring tuple structs/variants with an infallible single-armed match
- https://github.com/rust-lang/rust-clippy/pull/2684
#+begin_src rust
enum Wrapper {
    Data(i32),
}
fn main() {
    let wrapper = Wrapper::Data(42);
    let Wrapper::Data(data) = wrapper;
    println!("{:?}", data)
}
#+end_src

#+RESULTS:
: 42

* atomics and memory ordering
reasons to use atomic types
- if there is shared access to some memory value, we need to have additional information
  - about that access to let CPU know when should different threads see the operations that other threads do. Which operations are visible to threads that share memory
  - how they syncronize
  - when one thread writes to a value and other reads it, what are the guarantees which values the reader will read
    - will it always read the latest one?
    - what does "latest" even mean?
- it makes sense to have different API for atomic types, because when working with atomic types, we're actually issuing different instructions to the CPU (limitations on what code the compiler is allowed to generate).
* curst of rust
** lifetime annotations
*** 19:35 "tick `a` here and tick `a` here, they're the same think of it like generic over lifetime"
*** 33:10 =impl<T> ARST<T>= vs =impl ARST<T>=
*** =let ref mut reminders = self.reminder?;= is and inverse of =let reminder = &mut self.reminder?;=
*** =.take()= takes the value away (pops it), and sets orgiginal variable to =None=
*** =.as_mut()= implementation: =impl<T> Option<T> { fn as_mut(&mut self) -> Option<&mut T> }=
*** strings
#+begin_src rust
// ~> = similar
// => = construct

str ~> [char]         // sequence of characters,
                      // doesn't know how long

&str ~> &[char]       // fat pointer
                      // can point anywhere (stack,heap,static memory)

String ~> Vec<char>   // heap allocated, can shrink and grow
                      // dynamically expandable and contractable

String => &str        // (cheap -- AsRef)

&str => String        // (expensive -- Clone/memcpy)
                      // has to be done by heap allocation,
                      // and copying all characters
#+end_src
*** fat pointer vs shallow pointer
Fat pointer stores both start of the slice and lenght of the slice

* COMMENT Is it possible to define structs at runtime or otherwise achieve a similar effect?
No, it is not possible.

Simplified, at compile time, the layout (ordering, offset, padding, etc.) of every struct is computed, allowing the size of the struct to be known. When the code is generated, all of this high-level information is thrown away and the machine code knows to jump X bytes in to access field foo.

None of this machinery to convert source code to machine code is present in a Rust executable. If it was, every Rust executable would probably gain several hundred megabytes (the current Rust toolchain weighs in at 300+MB).

Other languages work around this by having a runtime or interpreter that is shared. You cannot take a Python source file and run it without first installing a shared Python interpreter, for example.

Additionally, Rust is a statically typed language. When you have a value, you know exactly what fields and methods are available. There is no way to do this with dynamically-generated structs — there's no way to tell if a field/method actually exists when you write the code that attempts to use it.

As pointed out in the comments, dynamic data needs a dynamic data structure, such as a HashMap.


* comment crazy cool things with =Range=
https://ridiculousfish.com/blog/posts/least-favorite-rust-type.html
#+begin_src rust
fn main() {
    let r = vec![1, 2, 3]..=vec![10, 11, 12];
    for i in r {
        println!("{:?}", i);
    }
}
#+end_src

* comment cool if let patter matching
#+begin_src rust
fn main() {
    let gfg = 2;
    let gfg_answer = if let v @ 0..=3 = gfg {
        format!("{}{}", "dsa=",v)
    } else {
        "fff".to_string()
    };
    println!("{}", gfg_answer);
}
#+end_src

#+RESULTS:
: dsa=2

* comment cool methods on option
#+begin_src rust
fn main() {
    let mut o = Some(5);
    let x = o.take().map(|uu| uu + 5);
    println!("{:?}", x);
}
#+end_src

#+RESULTS:
: Some(10)
* comment mutability
- immutability
- mutability
- inherited mutability
- interior mutability
